name: rag-project-env
channels:
  - pytorch
  - ajutla
  - conda-forge
  - defaults

dependencies:
# === Conda Packages ===
  - python=3.12
  - numpy<2.0.0
  - pytorch
  - llama-index
  - llama-index-core
  - llama-index-embeddings-huggingface
  - python-dotenv
  - sentence-transformers
  - ragas
  - pip

# === Pip Packages ===
  - pip:
    - llama-index-llms-google-genai
    - llama-index-llms-groq